### ISSUE TITLE
은수언니가 main 코드를 완료해서 댓글에 남겨주세요

### ISSUE THREAD

**Issue by kyunagaeee** [kyunagaeee/sooksoft#1]
은수언니 8시 30분까지 공유해주세요!

**Comment by lololololdy1113** [comment]
네

**Comment by EunsueBaek** [comment]
main.c 코드입니당

#include <stdio.h>
#include "Log.h"
#include "start.h"
#include "home.h"

main(){
	char* id;
	start();
//데이터베이스에 저장된 아이디를 id에 저장해야댐.
	ViewHome(id);
}

**Comment by EunsueBaek** [comment]
올렸습미당ㅎㅎ
