### ISSUE TITLE
9시까지 각자 지금까지 만든 코드 올려주세요

### ISSUE THREAD

**Issue by lololololdy1113** [kyunagaeee/sooksoft#2]
각자 지금까지 만든 코드들 수합을 위해 4일 오후 9시까지 올려주세요!

**Comment by EunsueBaek** [comment]
main.c 코드입니당

#include <stdio.h>
#include "Log.h"
#include "start.h"
#include "home.h"

main(){
	char* id;
	start();
//데이터베이스에 저장된 아이디를 id에 저장해야댐.
	ViewHome(id);
}

**Comment by EunsueBaek** [comment]
Phonebook.h 입니당

void Phonebook();

**Comment by EunsueBaek** [comment]
Schedule.h 입니당
void Schedule();

**Comment by kyunagaeee** [comment]
#include<stdio.h>

void Schedule(void);
void Add(void);
void View(void);
void Home(void);
void Delete(void); //void?

int main(){
	Schedule();}

void Schedule(){
	int choice=0;	
	printf("\n1.Add\n2.View\n3.Home\n원하는 작업 번호를 입력하세요.\n");
	scanf("%d",&choice);
	if(choice==1)
		Add();
	else if(choice==2)
		View();
	else
		Home();
		
}
void Add(){
	int date[6];
	char description[8];
	int choice=0;

	printf("\n일정을 등록하실 날짜를 6자리로 입력하세요.(ex.161225)\n");
		scanf("%d",&date);
		//이때 date 입력값 확인, date 를 또 다른데에 저장해야되지않음??

		printf("\n내용을 입력하세요.(7자리로)\n");
		scanf("%s",&description);

		printf("1. save\n2. exitadd\n수행할 작업의 번호를 입력하세요.\n");
		scanf("%d",&choice);
		if(choice==1)
			;
			//저장한다
		else
			Schedule();


}

void View(){
	int choice=0;
	printf("1. delete\n2. 뒤로가기\n수행할 작업의 번호를 입력하세요.\n");
		scanf("%d",&choice);
		if(choice==1)
			Delete();
		else
			Schedule();}

void Delete(){
}

**Comment by lololololdy1113** [comment]
#include <stdio.h>
#include <iostream>
#include <string>
using namespace std;

char name[20];
int phone[25];
string names[20];
string phones[20];
int idx;

void viewMenu();
void addPhonenum();
void checkPhonenum();
void storePhonenum();
void viewPhonebook();
void delCheck();
void delPhonenum(); 

void viewMenu(void) {
	int menu;
	printf("1. Add Phone number 2. Total phone book (Home : –1)");
	scanf("%d", &menu);
	if(menu==1)
		addPhonenum();
	else if (menu==2)
		viewPhonebook();
	//else if (menu==3)
	//Home();
}//viewMenu

void addPhoneum(void) {
	printf("이름과 전화번호를 입력해주세요 (ex) 김김김 01099998888) : ");
	scanf("%s %s", name, phone);
	checkPhonenum(name, phone);
}

void checkPhonenum(char name[], int phone[]) {
	if(!name || !phone) {
		printf("이름과 전화번호를 형식에 맞춰서 입력해주세요.\n");
		addPhonenum();
	}
	else 
		storePhonenum(name, phone);
}

void storePhonenum(char name[], int phone[]) {
	//2차원배열에 저장해야함
}

void viewPhonebook() {
	printf("index  |   name   |   PhoneNumber ");
	for(int i=0;;)
}

void delcheck() {
//전화번호 확인
}

void delPhonenum {
//삭제
}

int main() {
	viewMenu();
}//main

**Comment by EunsueBaek** [comment]
home.c 입니당

#include <stdio.h>
#include "home.h"
#include "account.h"
#include "Schedule.h"
#include "Phonebook.h"
#include "Log.h"

int ViewHome(char* id){
	int jobnum;
	
	printf(" %s 's 홈 화면\n",id);
	printf("\n ------------------- \n",id);
	printf("\t 1. Account Update \n");
	printf("\t 2. Phoe book \n");
	printf("\t 3. Schedule \n");
	printf("\t 4. Logout \n");
	printf(" 중 수행할 작업번호를 입력하세요. \n");
	scanf("%d",&jobnum);
	JobPerformAtHome(jobnum);
}

void JopPerformAtHome(int jobnum){
	if (jobnum == 1){
		AccUpdate();
	}
	else if (jobnum == 2){
		Phonebook();
	}
	else if ( jobnum == 3){
		Schedule();
	}
	else if (jobnum == 4){
		Logout();
	}
	else
		ErrMsg();
}

**Comment by EunsueBaek** [comment]
Log.c 입니당

#include <stdio.h>
#include "Log.h"

void Login(){
	char *ID_user_typed, *pswd_user_typed;
	printf("ID(첫 로그인시 0000, 종료 시 0 입력) :");
	ID_user_typed = InputS();
	/*사용자 앙이디랑 맞는지 체크 by(check(ID_user_typed,원래꺼)*/
	printf("비밀번호(첫 로그인시 0000, 종료 시 0 입력) :");
	pswd_user_typed = InputS();
	scanf("%s",&ID_user_typed);
	/*사용자 비밀번호랑 맞는지 체크 by(check(ID_user_typed,원래꺼)*/
	printf("로그인 성공");
}

char *InputS(){
	char *user_typed;
	scanf("%s",&user_typed);
	return user_typed;
}

**Comment by EunsueBaek** [comment]
start.c입니당

#include <stdio.h>
#include "start.h"

void start(){
	printf("WELCOME SCHEDULE MANAGER");
	Login();
}

void exits(){
	printf("프로그램이 종료됩니다.");
	exit(0);
}

**Comment by EunsueBaek** [comment]
account.h입니당

void AccUpdate();
void AccErrmsg();
int Input();
void ErrMsg();
void ChgeID();
void ChgePswd();

**Comment by EunsueBaek** [comment]
home.h 입니당

int ViewHome(char* id);
void JobPerformAtHome(int jobnumber);

**Comment by EunsueBaek** [comment]
Log.h입니당

void Login();
void Logout();
char* InputS();
int Check(char* a, char* b);

**Comment by EunsueBaek** [comment]
start.h입니당

#include <stdlib.h>
#include "Log.h"

void start();
void exits();

**Comment by Shuouou** [comment]
home.c 입니당

#include <stdio.h>
#include "home.h"
#include "account.h"
#include "Schedule.h"
#include "Phonebook.h"
#include "Log.h"

int ViewHome(char* id){
	int jobnum;
	
	printf(" %s 's 홈 화면\n",id);
	printf("\n ------------------- \n",id);
	printf("\t 1. Account Update \n");
	printf("\t 2. Phoe book \n");
	printf("\t 3. Schedule \n");
	printf("\t 4. Logout \n");
	printf(" 중 수행할 작업번호를 입력하세요. \n");
	scanf("%d",&jobnum);
	JobPerformAtHome(jobnum);
}

void JopPerformAtHome(int jobnum){
	if (jobnum == 1){
		AccUpdate();
	}
	else if (jobnum == 2){
		Phonebook();
	}
	else if ( jobnum == 3){
		Schedule();
	}
	else if (jobnum == 4){
		Logout();
	}
	else
		ErrMsg();
}

**Comment by Shuouou** [comment]
main.c입니당

#include <stdio.h>
#include "Log.h"
#include "start.h"
#include "home.h"

main(){
	char* id;
	start();
//데이터베이스에 저장된 아이디를 id에 저장해야댐.
	ViewHome(id);
}

**Comment by Shuouou** [comment]
Log.c입니다

char *InputS(){
	char *user_typed;
	scanf("%s",&user_typed);
	return user_typed;
}

**Comment by Shuouou** [comment]
start.c입니당

#include <stdio.h>
#include "start.h"

void start(){
	printf("WELCOME SCHEDULE MANAGER");
	Login();
}

void exits(){
	printf("프로그램이 종료됩니다.");
	exit(0);
}

**Comment by Shuouou** [comment]
void AccUpdate();
void AccErrmsg();
int Input();
void ErrMsg();
void ChgeID();
void ChgePswd();

//account.h 입니당

**Comment by Shuouou** [comment]
int ViewHome(char* id);
void JobPerformAtHome(int jobnumber);

//home.h입니당

**Comment by Shuouou** [comment]
void Login();
void Logout();
char* InputS();
int Check(char* a, char* b);

//Log.h입니당

**Comment by Shuouou** [comment]
void Phonebook();

//Phonebook.h입니당

**Comment by Shuouou** [comment]
void Schedule();

//Schedule.h입니당

**Comment by Shuouou** [comment]
#include <stdlib.h>
#include "Log.h"

void start();
void exits();

//start.h입니당
