### ISSUE TITLE
@경애 schedule기능 함수들 이름 변경 부탁드립니다

### ISSUE THREAD

**Issue by lololololdy1113** [kyunagaeee/sooksoft#9]
다른 기능의 함수들과 헷갈릴 수 있으니까 add랑 view를 addSchedule처럼 구체적인 주체를 넣는게 좋을 것 같아요

**Comment by kyunagaeee** [comment]
void Schedule(){
int choice=0;
printf("\n1.Add\n2.View\n3.Home\n원하는 작업 번호를 입력하세요.\n");
scanf("%d",&choice);
if(choice==1)
Add();
else if(choice==2)
View();
else
Home();

}
void Add(){
int date[6];
char description[8];
int choice=0;

printf("\n일정을 등록하실 날짜를 6자리로 입력하세요.(ex.161225)\n");
	scanf("%d",&date);
	//이때 date 입력값 확인, date 를 또 다른데에 저장해야되지않음??

	printf("\n내용을 입력하세요.(7자리로)\n");
	scanf("%s",&description);

	printf("1. save\n2. exitadd\n수행할 작업의 번호를 입력하세요.\n");
	scanf("%d",&choice);
	if(choice==1)
		;
		//저장한다
	else
		Schedule();
}

**Comment by kyunagaeee** [comment]
올렸습니다~

**Comment by lololololdy1113** [comment]
감사합니다!
